export const GET_USER_DATA_STARTED = "GET_USER_DATA_STARTED";
export const GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS";
export const GET_USER_DATA_FAILURE = "GET_USER_DATA_FAILURE";

export const SET_IS_REQUESTING_TRUE = "SET_IS_REQUESTING_TRUE";
export const SET_IS_REQUESTING_FALSE = "SET_IS_REQUESTING_FALSE";

export const SET_SHOW_NOTIFICATION_TRUE = "SET_SHOW_NOTIFICATION_TRUE";
export const SET_SHOW_NOTIFICATION_FALSE = "SET_SHOW_NOTIFICATION_FALSE";